import { createFileRoute, Link } from "@tanstack/react-router";

import { LegalPage } from "@/components/LegalPage";
import { SITE, absoluteUrl } from "@/config/site";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Ezvor" },
      { name: "description", content: "The rules for using Ezvor." },
    ],
    links: [{ rel: "canonical", href: absoluteUrl("/terms") }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <section>
        <p>
          By using {SITE.name} you agree to these terms. If you don&apos;t agree, please don&apos;t
          use the service.
        </p>
      </section>

      <section>
        <h2>The service</h2>
        <p>
          {SITE.name} is provided free of charge, as is, without warranties. Features may change or
          be unavailable at times. We aren&apos;t liable for losses from using it, to the extent the
          law allows.
        </p>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <ul>
          <li>Don&apos;t submit code meant to attack, overload or escape the code runners.</li>
          <li>
            Don&apos;t abuse the AI features, scrape the site at scale, or bypass rate limits.
          </li>
          <li>
            Don&apos;t impersonate others or post unlawful or abusive content in your profile.
          </li>
          <li>One account per person; keep your sign-in secure.</li>
        </ul>
        <p>We may suspend accounts that break these rules.</p>
      </section>

      <section>
        <h2>Your content</h2>
        <p>
          You own the code, notes and messages you create. You give us permission to store and
          process them to run the service, as described in the{" "}
          <Link to="/privacy">Privacy Policy</Link>.
        </p>
      </section>

      <section>
        <h2>AI-generated content</h2>
        <p>
          Hints, editorials, solutions and advice are generated by AI and can be wrong. Verify
          important information yourself, especially career decisions and application deadlines.
        </p>
      </section>

      <section>
        <h2>Third-party content</h2>
        <p>
          Problem statements, job listings and opportunity details come from public third-party
          sources and belong to their owners. Links to other sites aren&apos;t endorsements.
        </p>
      </section>

      <section>
        <h2>Changes and contact</h2>
        <p>
          We may update these terms; the date above shows the latest version. Questions: open an
          issue at{" "}
          <a href={`${SITE.github}/issues`} target="_blank" rel="noopener noreferrer">
            {SITE.github.replace(/^https:\/\//, "")}
          </a>
          .
        </p>
      </section>
    </LegalPage>
  );
}
