/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CompilerRouteImport } from './routes/compiler'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PHandleRouteImport } from './routes/p.$handle'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedAdvisorIndexRouteImport } from './routes/_authenticated/advisor.index'
import { Route as AuthenticatedAdvisorThreadIdRouteImport } from './routes/_authenticated/advisor.$threadId'
import { Route as ApiPublicHooksRefreshStatusesRouteImport } from './routes/api/public/hooks/refresh-statuses'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilerRoute = CompilerRouteImport.update({
  id: '/compiler',
  path: '/compiler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdvisorIndexRoute =
  AuthenticatedAdvisorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdvisorRoute,
  } as any)
const AuthenticatedAdvisorThreadIdRoute =
  AuthenticatedAdvisorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAdvisorRoute,
  } as any)
const ApiPublicHooksRefreshStatusesRoute =
  ApiPublicHooksRefreshStatusesRouteImport.update({
    id: '/api/public/hooks/refresh-statuses',
    path: '/api/public/hooks/refresh-statuses',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compiler': typeof CompilerRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/problems': typeof ProblemsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/advisor': typeof AuthenticatedAdvisorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/p/$handle': typeof PHandleRoute
  '/advisor/$threadId': typeof AuthenticatedAdvisorThreadIdRoute
  '/advisor/': typeof AuthenticatedAdvisorIndexRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compiler': typeof CompilerRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/problems': typeof ProblemsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/p/$handle': typeof PHandleRoute
  '/advisor/$threadId': typeof AuthenticatedAdvisorThreadIdRoute
  '/advisor': typeof AuthenticatedAdvisorIndexRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compiler': typeof CompilerRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/problems': typeof ProblemsRoute
  '/readiness': typeof ReadinessRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/p/$handle': typeof PHandleRoute
  '/_authenticated/advisor/$threadId': typeof AuthenticatedAdvisorThreadIdRoute
  '/_authenticated/advisor/': typeof AuthenticatedAdvisorIndexRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compiler'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/problems'
    | '/readiness'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/advisor'
    | '/api/chat'
    | '/p/$handle'
    | '/advisor/$threadId'
    | '/advisor/'
    | '/api/public/hooks/refresh-statuses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compiler'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/problems'
    | '/readiness'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/api/chat'
    | '/p/$handle'
    | '/advisor/$threadId'
    | '/advisor'
    | '/api/public/hooks/refresh-statuses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compiler'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/problems'
    | '/readiness'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/_authenticated/advisor'
    | '/api/chat'
    | '/p/$handle'
    | '/_authenticated/advisor/$threadId'
    | '/_authenticated/advisor/'
    | '/api/public/hooks/refresh-statuses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompilerRoute: typeof CompilerRoute
  GraphRoute: typeof GraphRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProblemsRoute: typeof ProblemsRoute
  ReadinessRoute: typeof ReadinessRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  PHandleRoute: typeof PHandleRoute
  ApiPublicHooksRefreshStatusesRoute: typeof ApiPublicHooksRefreshStatusesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiler': {
      id: '/compiler'
      path: '/compiler'
      fullPath: '/compiler'
      preLoaderRoute: typeof CompilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor/': {
      id: '/_authenticated/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AuthenticatedAdvisorIndexRouteImport
      parentRoute: typeof AuthenticatedAdvisorRoute
    }
    '/_authenticated/advisor/$threadId': {
      id: '/_authenticated/advisor/$threadId'
      path: '/$threadId'
      fullPath: '/advisor/$threadId'
      preLoaderRoute: typeof AuthenticatedAdvisorThreadIdRouteImport
      parentRoute: typeof AuthenticatedAdvisorRoute
    }
    '/api/public/hooks/refresh-statuses': {
      id: '/api/public/hooks/refresh-statuses'
      path: '/api/public/hooks/refresh-statuses'
      fullPath: '/api/public/hooks/refresh-statuses'
      preLoaderRoute: typeof ApiPublicHooksRefreshStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdvisorRouteChildren {
  AuthenticatedAdvisorThreadIdRoute: typeof AuthenticatedAdvisorThreadIdRoute
  AuthenticatedAdvisorIndexRoute: typeof AuthenticatedAdvisorIndexRoute
}

const AuthenticatedAdvisorRouteChildren: AuthenticatedAdvisorRouteChildren = {
  AuthenticatedAdvisorThreadIdRoute: AuthenticatedAdvisorThreadIdRoute,
  AuthenticatedAdvisorIndexRoute: AuthenticatedAdvisorIndexRoute,
}

const AuthenticatedAdvisorRouteWithChildren =
  AuthenticatedAdvisorRoute._addFileChildren(AuthenticatedAdvisorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompilerRoute: CompilerRoute,
  GraphRoute: GraphRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProblemsRoute: ProblemsRoute,
  ReadinessRoute: ReadinessRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapsRoute: RoadmapsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  PHandleRoute: PHandleRoute,
  ApiPublicHooksRefreshStatusesRoute: ApiPublicHooksRefreshStatusesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
