/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicHooksRefreshStatusesRouteImport } from './routes/api/public/hooks/refresh-statuses'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshStatusesRoute =
  ApiPublicHooksRefreshStatusesRouteImport.update({
    id: '/api/public/hooks/refresh-statuses',
    path: '/api/public/hooks/refresh-statuses',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/graph': typeof GraphRoute
  '/opportunities': typeof OpportunitiesRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/hooks/refresh-statuses': typeof ApiPublicHooksRefreshStatusesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/public/hooks/refresh-statuses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/public/hooks/refresh-statuses'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/graph'
    | '/opportunities'
    | '/playground'
    | '/resources'
    | '/roadmaps'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/public/hooks/refresh-statuses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  GraphRoute: typeof GraphRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksRefreshStatusesRoute: typeof ApiPublicHooksRefreshStatusesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-statuses': {
      id: '/api/public/hooks/refresh-statuses'
      path: '/api/public/hooks/refresh-statuses'
      fullPath: '/api/public/hooks/refresh-statuses'
      preLoaderRoute: typeof ApiPublicHooksRefreshStatusesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  GraphRoute: GraphRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapsRoute: RoadmapsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksRefreshStatusesRoute: ApiPublicHooksRefreshStatusesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
